# Generated by Django 3.2.6 on 2021-09-01 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doc_app', '0003_rename_user_id_document_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
