# Generated by Django 3.2.6 on 2021-08-28 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateTimeField(verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=100)),
                ('Release_date', models.DateTimeField()),
                ('Language', models.CharField(max_length=100)),
                ('Length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('Awards_received', models.ManyToManyField(blank=True, to='idmpapp.Award')),
                ('artists', models.ManyToManyField(blank=True, to='idmpapp.Artist')),
            ],
        ),
    
    ]
