# Generated by Django 3.2.6 on 2021-08-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=100)),
                ('Release_date', models.DateField()),
                ('Language', models.CharField(max_length=100)),
                ('Length', models.DecimalField(decimal_places=2, max_digits=3)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Artist', models.ManyToManyField(to='idmpapp.Artist')),
                ('Awards_received', models.ManyToManyField(null=True, to='idmpapp.Awards')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Rubbish'), (2, '2 - Worst'), (3, '3 - Horrible'), (4, '4 - Bad'), (5, '5 - Below Average'), (6, '6 - Average'), (7, '7 - Nice'), (8, '8 - Awesome'), (9, '9 - Perfect'), (10, '10 - Mind blowing')])),
                ('votes', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idmpapp.movie')),
            ],
        ),
    ]
