# Generated by Django 3.2.6 on 2021-08-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idmpapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Awards',
        ),
        migrations.AlterField(
            model_name='movie',
            name='Awards_received',
            field=models.ManyToManyField(null=True, to='idmpapp.Award'),
        ),
    ]
