# Generated by Django 3.2.6 on 2021-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idmpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Artist',
            field=models.ManyToManyField(blank=True, to='idmpapp.Artist'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Awards_received',
            field=models.ManyToManyField(blank=True, null=True, to='idmpapp.Award'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
