# Generated by Django 3.2.6 on 2021-08-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idmpapp', '0002_auto_20210825_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Awards_received',
            field=models.ManyToManyField(blank=True, to='idmpapp.Award'),
        ),
    ]
